---
title: "1. Make source data grids"
description: >
  This vignette shows how to build the netCDF data file and then
  update it to new start and end dates.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{1. Make source data grids}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4L, tibble.print_max = 4L)
```

```{r setup}
library(BOMcatchr)
```
This example shows how to build the required data file, plot date that the file variables were built and then update it.

## Make netCDF file
This example shows the steps required to build the netCDF data grid file.

First, let's define the dates for the data grids. Here the data grids are created for data between the dates \code{updateTo} and \code{updateTo}. If the latter two dates were not input then data would be downloaded from 1/1/1900 to yesterday.

Note, in practice users often run \code{grid_build} once to build the netCDF data file that contain all variables over the entire record length (which requires ~5GB disk storage) and then use the netCDF grids for multiple projects, rather than re-building the netCDF grids for each project.

```{r}
startDate <- as.Date(Sys.Date()-25,"%Y-%m-%d")
endDate <- as.Date(Sys.Date()-5,"%Y-%m-%d")
```

Next the file name for the netCDF grids need to be defined. Here we'll just use a temporary file. You should change this to a non-temporary file name and folder.
```{r}
ncdfFilename <- tempfile(fileext='.nc')
```

Now we're ready to download and build the netCDF grids.

The netCDF data file contains grids of daily rainfall, minimum and maximum temperature. Below, this will be updated to include vapour pressure and solar radiation for all of Australia.
```{r}
ncdffile.name <- grid_build(ncdfFilename=ncdfFilename,
                updateFrom=startDate,
                updateTo=endDate,
                vars = c('precip','tmin','tmax'))
```

Now let's get a summary of when the the netCDF source data was created. Note, the output data.frame shows the gridded variables over the expected date range.
```{r}
summary.df <- BOMcatchr::grid_summary(ncdffile.name)
summary.df
```

The number of weather stations used to grid each time step

## Plot source data dates and required data updates
The BoM gridded data undergoes a detailed review and update process (see [https://www.bom.gov.au/climate/austmaps/about-rain-maps.shtml](here) and [https://www.bom.gov.au/climate/austmaps/update-schedule.shtml](here) ). Hence, the netCDF grids that one may have built some time ago may be require updating with revised BoM data.

To understand when each variable and time-step was built, and which needs updating, the netCDF data can be examined against the above BoM update schedules - see \code{grid_sources()} for details. The plot below shows the date each time-step of each variable was created. The output from \code{grid_ages} reports if any variables can be updated. Note, the input \code{today} is ONLY used for testing and should not be input during regular use. Here today is set to 12 days into the future.
```{r}
#| fig.width = 8,
#| fig.height = 3

summary.ages <- BOMcatchr::grid_ages(ncdffile.name,
                                     today = Sys.Date()+12,
                                     plot.sourcedate = T)
```

## Plot the number of weather stations used to make grids
The number of weather stations used to create each grid changes over time, which can provide a measure of grid reliability. We can extract the number of stations per variable as follows:
```{R}
nstations <- BOMcatchr::extract_nstations(ncdffile.name)
```
Now let's plot the number of stations over time.
```{R}
#| fig.width = 8,
#| fig.height = 6

 nvars = length(nstations)
 par(mfrow=c(nvars,1), mar =  c(5, 7.5, 4, 2.7) + 0.1)

 for (i in 1:nvars) {
    xdata = nstations[[i]]$Date
    ydata = nstations[[i]]$n_stations

    plot(xdata,
         ydata,
         main = names(nstations)[i],
         ylab = 'Number stations',
         xlab = 'Date',
         type='l')
 }
```
## Update an existing variable

Now that we've built the above file, the updating can be demonstrated.

The package allows for such updating between user defined dates. Here we'll update the data between the dates defined prior. Also, note that \code{vars} is not defined. This will cause all variables in the original file to be updated. That said, individual variables can be updated.

```{r}
ncdffile.name <- grid_build(ncdfFilename=ncdffile.name,
                updateFrom=startDate,
                updateTo=endDate)
```

## Add a variable to existing data grids

Here we'll update the data grids to also include vapour pressure. Here the same date range will be used. Because the date range of the new variable equals the date range of the existing variables, only vapour pressure data is updated. This feature can be used to update the data of a single variable as required.

```{r}
ncdffile.name <- grid_build(ncdfFilename=ncdffile.name,
                updateFrom=startDate,
                updateTo=endDate,
                vars = c('vprp_3pm'))
```

Now let's check that the file includes both the original three variable plus vapour pressure.
```{r}
summary.df <- BOMcatchr::grid_summary(ncdffile.name)
summary.df
```
## Add a variable to existing data grids and update other variables

Now lets add solar radiation. Here an earlier start date will be used. However, because the date range of all variables within the netCDF file must be equal, the date range of the other variables must also be updated.

```{r}
startDate <- startDate - 5
```

```{r}
ncdffile.name <- grid_build(ncdfFilename=ncdffile.name,
                updateFrom=startDate,
                updateTo=endDate,
                vars = c('solarrad'))
```

Now let's check that the file includes both the prior four variables plus solar radiation.
```{r}
summary.df <- BOMcatchr::grid_summary(ncdffile.name)
summary.df
```

And finally, again let's plot the source data age of the grids (note, for the demonstration we're again assuming it is 12 days into the future).
```{r}
#| fig.width = 8,
#| fig.height = 3

summary.ages <- BOMcatchr::grid_ages(ncdffile.name,
                                     today = Sys.Date()+12,
                                     plot.sourcedate = T)
```
