---
title: "Reliability of point daily and monthly data"
description: >
  This vignette demonstrates the reliability of the package by comparing extracted data against observations from six rainfall and temperate gauges. The building and extraction of data at user-defined time-step is first demonstrated.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reliability of point daily and monthly data}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4L, tibble.print_max = 4L)
```

```{r setup}
library(BOMcatchr)
```
This example demonstrates the reliability of the package by comparing extracted data against observations from six rainfall and temperate gauges. The building and extraction of data at user-defined time-step is first demonstrated.

## Make netCDF file
The first step is to create the netCDF files. Here the netCDF file is created and only for daily and monthly precipitation data. Note, the monthly precipitation product can slightly differ from the monthly sum of the daily precipitation product. See \url{https://www.bom.gov.au/climate/austmaps/about-rain-maps.shtml} for details.

Here the data is only downloaded between the dates \code{dataFrom} and \code{dataTo}. If the latter two dates were not input then data would be downloaded from 1/1/1900 to yesterday.
```{r}
dataFrom = as.Date("2010-01-01","%Y-%m-%d")
dataTo = as.Date("2010-12-31","%Y-%m-%d")
```

The netCDF file contains grids of daily rainfall for all of Australia and is used below to extract data at points of interest. Often users run \code{grid_build} once to build netCDF data files that contain all variables over the entire record length (which requires ~5GB disk storage) and then use the netCDFs grids for multiple projects, rather than re-building the netCDF for each project. Also, if \code{grid_build} is run with the the netCDF file name pointing to existing files and \code{updateFrom=NA} then the netCDF files will be updated to yesterday.

To start to create the grids, the file name for the netCDF grids needs to be defined. Here we'll just use a temporary file. You should change this to a non-temporary file name and folder.
```{r}
ncdfFilename = tempfile(fileext='.nc')
```
Now with the inputs defined we can download the gridded data and build the netCDF file. Note, here \code{vars} is set to only download daily precipitation.
```{r}
fnames = grid_build(ncdfFilename = ncdfFilename,
                         updateFrom = dataFrom,
                         updateTo = dataTo,
                         vars = c('tmax', 'precip', 'precip.monthly'))
```

## Set the points for data extraction and map
With the data grids built, let's load for the coordinates for the four example weather gauges and then convert them to a terra spatial vector object and the projection set to GDA94.
```{r}
data("weather_gauge_loc")

coords = terra::vect(weather_gauge_loc,
                     crs = '+proj=longlat +ellps=GRS80 +no_defs',
                     geom = c("longitude", "latitude")
                     )

n_sites = nrow(coords)
```
Now let's download a polygon of Australia and map the extraction location on top of it (as red circles).

```{r}
#| fig.width = 5,
#| fig.height = 4

st = extract_locations('state',id=NA)

terra::plot(st)
terra::plot(coords, , col='red',add=T)
terra::text(coords, labels=coords$site_ID, halo=TRUE, jitter = 8)

terra::add_legend('bottomleft',
                  legend = c('States and Territories', 'Weather gauge'),
                  col=c('black','red'),
                  pch = c(NA,16),
                  lty=c(1,NA)
                  )
```

## Extract gridded data
Now let's extract the gridded data at the four locations. The data is extracted from the netCDF file \code{ncdfFilename} and between the dates \code{extractFrom} and \code{extractTo}.

Note the netCDF file \code{ncdfFilename} must be in the working directory or the full file path must be given.
```{r}
extracted.data = extract_data(ncdfFilename = ncdfFilename,
                                        extractFrom = dataFrom,
                                        extractTo = dataTo,
                                        locations = coords,
                                        vars = c('tmax', 'precip'),
                                        ET.function='')
```

## Plot the extracted data over time
Now let's plot time series of the extracted daily precipitation and maximum temperature.

```{r}
#| fig.width = 8,
#| fig.height = 12


par(mfrow = c(n_sites, 2), cex = 0.5)
for (i in 1:n_sites){
  filt = extracted.data$Location.ID == coords$site_ID[i]

  dates = ISOdate(extracted.data$year[filt],
                  extracted.data$month[filt],
                  extracted.data$day[filt])

  data2plot = extracted.data$precip[filt]
  plot(dates, data2plot,
       main = paste('Extracted precip. at',coords$site_ID[i]),
       ylab = 'Precip [mm/d]',
       xlab = 'Date',
       type = 'l')

  data2plot = extracted.data$tmax[filt]
  plot(dates, data2plot,
       main = paste('Extracted max. temperature at',coords$site_ID[i]),
       ylab = 'Max. temp [C]',
       xlab = 'Date',
       type = 'l')
}
```

## Check extracted data against gauge data
To assess the reliability of the extracted rain gauge data, let's use the following observed precipitation for 2010 (from gauge_63005), sourced from the Australian Bureau of Meteorology.
```{r}
data("weather_gauge_obs")
```
Now let's compare the extracted data against the gauge data.

The left column shows the gauge and extracted daily precipitation. Similarly, the middle column shows that for the commutative daily precipitation and the right column shows that for the daily maximum temperature. All plots include the 1:1 line. Overall, the results show that the gridded rainfall can have a RMSE of a few mm/day while the temperature generally has a low RMSE of less and one degree. The daily bias is less than 1 mm/day at all gauges.

```{r}
#| fig.width = 8,
#| fig.height = 12
par(mfrow = c(n_sites, 3),
    mar = c(5, 5, 1.5, 1.5),
    pty = "s",
    cex = 0.5)

for (i in 1:n_sites){

  filt_obs = weather_gauge_obs$site_ID == coords$site_ID[i]
  xdata = weather_gauge_obs[ which(filt_obs), ]$precip_mmday

  filt_grd = extracted.data$Location.ID == coords$site_ID[i]
  ydata = extracted.data[filt_grd, ]$precip

  filt_obsErr = !(is.na(xdata) | xdata == -999)
  xdata = xdata[ filt_obsErr ]
  ydata = ydata[ filt_obsErr ]

  shared_limits <- range(c(xdata, ydata))
  plot(xdata,
       ydata,
       xlim = shared_limits,
       ylim = shared_limits,
       asp = 1,
       main = paste('Site', coords$site_ID[i], 'precip.'),
       xlab = 'Obs. [mm/d]',
       ylab = 'Extracted precip. [mm/d]')
  abline(0,1, col='grey', lty=2)
  rmse = round(sqrt(mean((xdata - ydata)^2)), 2)
  bias = round(mean(xdata - ydata), 1)
  text(x=shared_limits[1], y=shared_limits[2]*0.9, adj = c(0,0),
       labels = paste('RMSE = ', rmse, 'mm/day'))
  text(x=shared_limits[1], y=shared_limits[2]*0.8, adj = c(0,0),
       labels = paste('Bias = ', bias, 'mm/day'))

  xdata = cumsum(xdata)
  ydata = cumsum(ydata)
  shared_limits <- range(c(xdata, ydata))
  plot(xdata,
       ydata,
       xlim = shared_limits,
       ylim = shared_limits,
       asp = 1,
       main = paste('Site', coords$site_ID[i], 'cum. precip.'),
       xlab = 'Obs. [mm]',
       ylab = 'Extracted precip. [mm]',
       type = 'l')
  abline(0,1, col='grey', lty=2)

  xdata = weather_gauge_obs[ which(filt_obs), ]$tmax_C
  ydata = extracted.data[ filt_grd, ]$tmax

  filt_obsErr = !(is.na(xdata) | xdata == -999)
  xdata = xdata[ filt_obsErr ]
  ydata = ydata[ filt_obsErr ]
  shared_limits <- range(c(xdata, ydata))
  plot(xdata,
       ydata,
       xlim = shared_limits,
       ylim = shared_limits,
       asp = 1,
       main =paste('Site', coords$site_ID[i], 'max. T.'),
       xlab ='Obs. [C]',
       ylab ='Extracted tmax [C]')
  abline(0,1, col='grey', lty=2)
  rmse = round(sqrt(mean((xdata - ydata)^2)), 2)
  bias = round(mean(xdata - ydata), 1)
  text(x=shared_limits[1], y=shared_limits[2]*0.9, adj = c(0,0),
       labels = paste('RMSE = ', rmse, 'C'))
  text(x=shared_limits[1], y=shared_limits[2]*0.8, adj = c(0,0),
       labels = paste('Bias = ', bias, 'C'))
}
```

## Check extracted data against monthly precipitation gauge data

Now let's compare the gauge data at a monthly time step with the extracted monthly data and aggregated daily data to a monthly time scale.

First, let's extract the daily data at a monthly scale
```{r}
extracted.daily2monthly = extract_data(ncdfFilename = ncdfFilename,
                                        extractFrom = dataFrom,
                                        extractTo = dataTo,
                                        locations = coords,
                                        vars = c('precip'),
                                        temporal.timestep = 'monthly',
                                        temporal.fn.inner = 'sum',
                                        ET.function='')
```
Next let's extract the monthly data product.
```{r}
extracted.monthly = extract_data(ncdfFilename = ncdfFilename,
                                        extractFrom = dataFrom,
                                        extractTo = dataTo,
                                        locations = coords,
                                        vars = c('precip.monthly'),
                                        temporal.timestep = 'monthly',
                                        ET.function='')
```

Now we can compare the extracted estimates of monthly precipitation with the gauge monthly precipitation.

The left column shows the monthly gauged precipitation vs the extracted daily precipitation summed to monthly. It shows that the daily gridded data generally has a RMSE of 3-14 mm/month aand a low bias. The exception is 71041 at the Mt Thredo village, which is the only test gauge likely to be impacted by snow.

The centre column shows the monthly gauged precipitation vs the extracted monthly precipitation (i.e. the gridded monthly precipitation). It shows a comparable RMSE and bias to the daily gridded precipitation in the left column.

The right column shows the extracted monthly precipitation against the extracted daily precipitation summed to monthly. It shows that generally there is a low RMSE and bias, and hence there does not appear to be an obvious difference between the daily or monthly gridded precipitation products (as least for 2010).

```{r}
#| fig.width = 8,
#| fig.height = 12
par(mfrow = c(n_sites, 3),
    mar = c(5, 5, 1.5, 1.5),
    pty = "s",
    cex = 0.5)

for (i in 1:n_sites){
  xdata = weather_gauge_obs[ weather_gauge_obs$site_ID == as.numeric(coords$site_ID[i]), ]
  filt_obsErr = !(is.na(xdata$precip_mmday) | xdata$precip_mmday == -999)
  xdata = xdata[filt_obsErr, ]

  xdata = xts::as.xts(xdata[, 'precip_mmday'], order.by=xdata[, 'date'])
  xdata = xts::apply.monthly(xdata, apply, 2, 'sum')
  xdata = as.numeric(xdata[])

  filt = extracted.daily2monthly$Location.ID == coords$site_ID[i]
  ydata = extracted.daily2monthly[ filt, 'precip']

  shared_limits <- range(c(xdata, ydata))
  plot(xdata,
       ydata,
       xlim = shared_limits,
       ylim = shared_limits,
       asp = 1,
       main = paste('Site', coords$site_ID[i], 'summed daily precip.'),
       xlab ='Obs. [mm/d]',
       ylab ='Summed extracted precip. [mm/month]')
  abline(0,1, col='grey', lty=2)
  rmse = round(sqrt(mean((xdata - ydata)^2)), 1)
  bias = round(mean(xdata - ydata), 1)
  text(x=shared_limits[1], y=shared_limits[2]*0.9, adj = c(0,0),
       labels = paste('RMSE = ', rmse, 'mm/month'))
  text(x=shared_limits[1], y=shared_limits[2]*0.8, adj = c(0,0),
       labels = paste('Bias = ', bias, 'mm/month'))
  ydata = extracted.monthly$precip.monthly[filt]
  shared_limits <- range(c(xdata, ydata))
  plot(xdata,
       ydata,
       xlim = shared_limits,
       ylim = shared_limits,
       asp = 1,
       main = paste('Site', coords$site_ID[i], 'monthly precip.'),
       xlab ='Obs. [mm/d]',
       ylab ='Extracted precip. [mm/month]')
  abline(0,1, col='grey', lty=2)
  rmse = round(sqrt(mean((xdata - ydata)^2)), 1)
  bias = round(mean(xdata - ydata), 1)
  text(x=shared_limits[1], y=shared_limits[2]*0.9, adj = c(0,0),
       labels = paste('RMSE = ', rmse, 'mm/month'))
  text(x=shared_limits[1], y=shared_limits[2]*0.8, adj = c(0,0),
       labels = paste('Bias = ', bias, 'mm/month'))

  xdata = extracted.monthly$precip.monthly[filt]
  ydata = extracted.daily2monthly[ filt, 'precip']
  shared_limits <- range(c(xdata, ydata))
  plot(xdata,
       ydata,
       xlim = shared_limits,
       ylim = shared_limits,
       asp = 1,
       main = paste('Site', coords$site_ID[i], 'gridded monthly vs daily'),
       xlab ='Extracted monthly precip. [mm/month]',
       ylab ='Summed daily precip. [mm/month]')
  abline(0,1, col='grey', lty=2)
  rmse = round(sqrt(mean((xdata - ydata)^2)), 1)
  bias = round(mean(xdata - ydata), 1)
  text(x=shared_limits[1], y=shared_limits[2]*0.9, adj = c(0,0),
       labels = paste('RMSE = ', rmse, 'mm/month'))
  text(x=shared_limits[1], y=shared_limits[2]*0.8, adj = c(0,0),
       labels = paste('Bias = ', bias, 'mm/month'))
}
```
